Move HeaderNavigation and OrdinoFooter components to ordino
Caleydo/ordino_public pull request #84
Opened 2021-03-18 09:22 UTC by oltionchampari

Closes Caleydo/tdp_bi_bioinfodb#1200

### Summary 
see Caleydo/ordino#274

2021-03-18 09:25 UTC, oltionchampari commented
Build fails because it requires Caleydo/ordino#274

2021-03-22 20:25 UTC, thinkh requested changes
* Just some minor optimizations
* We can probably also remove the ordino.svg file here as it was moved to the _ordino_ repo. Please check for possible usages here again.

2021-03-22 20:25 UTC, thinkh commented on src/pages/DatasetsPage.tsx
> +import {HeaderNavigation} from 'ordino';
Imports can be combined.

2021-03-22 20:25 UTC, thinkh commented on src/pages/Error404Page.tsx
> +import {OrdinoFooter} from 'ordino';
Imports can be combined.

2021-03-22 20:25 UTC, thinkh commented on src/pages/FeaturesPage.tsx
> +import {OrdinoFooter} from 'ordino';
Imports can be combined.

2021-03-22 20:25 UTC, thinkh commented on src/pages/HelpPage.tsx
> +import {OrdinoFooter} from 'ordino';
Imports can be combined.

2021-03-22 20:25 UTC, thinkh commented on src/pages/NewsPage.tsx
> +import {OrdinoFooter} from 'ordino';
Imports can be combined.

2021-03-22 20:25 UTC, thinkh commented on src/pages/PublicationPage.tsx
> +import {OrdinoFooter} from 'ordino';
Imports can be combined.

2021-03-24 20:22 UTC, thinkh approved these changes
Looks good!

2021-03-24 20:26 UTC, merged